---
title: Jack Whiting
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  works:
    title: Works
    output: true
navigation:
  - title: About
    url: /about
  - title: Work
    url: /work
  - title: Blog
    url: /blog
  - title: Contact Me
    url: 'mailto:hi@jackwhiting.co.uk?subject=Hi Jack'
email: hi@jackwhiting.co.uk
baseurl:
url: https://jackwhiting.co.uk
enforce_ssl: https://jackwhiting.co.uk
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - octopress-autoprefixer
  - jekyll-redirect-from
