---
title: Jack Whiting
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
email: hi@jackwhiting.co.uk
baseurl: 
url: 
twitter_username: jackabox
github_username: jackabox
markdown: kramdown
sass:
  style: compressed
