---
title: Jack Whiting
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
email: hi@jackwhiting.co.uk
baseurl: //jackwhiting.co.uk
url: https://jackwhiting.co.uk
enforce_ssl: https://jackwhiting.co.uk
markdown: kramdown
sass:
  style: compressed
